---
- hosts: all
  port: 898
  sudo: yes
  tasks:
  - name: deploy mysql
    docker:
      docker_api_version: 1.15 
      name: "mysql" 
      image: "mysql"
      ports: "3306:3306"
      volumes: "/var/lib/engage/mysql:/var/lib/mysql"
      env: "MYSQL_ROOT_PASSWORD=123"
      state: started
      restart_policy: always
    tags: mysql

  - name: deploy webservice
    docker: 
      docker_api_version: 1.15 
      name: "webservice" 
      image: "yaelle/engage-ws:latest"
      volumes: "/home/engagevm/.m2/settings.xml:/root/.m2/settings.xml"
      ports: "8080:8080"
      links: "mysql:mysql"
      pull: always
      state: restarted
      memory_limit: 0
      restart_policy: always

  - name: deploy interface
    docker:
      docker_api_version: 1.15 
      name: "interface" 
      image: "yaelle/engage-interface:latest"
      ports: "80:80"
      env: "RAILS_ENV=production"
      links: "mysql:mysql,webservice:ws"
      dns: localhost
      pull: always
      state: restarted
      memory_limit: 0
      restart_policy: always
